version: '3.8'

services:
  web:
    image: php:8.2-fpm
    container_name: php-container
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    env_file:
      - .env
    command: >
      sh -c "apt-get update &&
             apt-get install -y default-mysql-client &&
             docker-php-ext-install pdo pdo_mysql &&
             php-fpm"

  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: tech_compare
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - ./src/config/database_schema.sql:/docker-entrypoint-initdb.d/database_schema.sql

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge